server:
  port: ${SERVICE_PORT:8083}

sidoc:
  rest:
    url: ${SIDOC_URL:http://190.242.101.171:10042}
    methods:
      login: "/user/login"
      client-info: "/client/info"
spring:
  datasource:
    url: ${PERSISTENCE_URL:jdbc:h2:mem:sbs_ms_schema;MODE=MYSQL}
    username: ${PERSISTENCE_USER:root}
    password: ${PERSISTENCE_PASSWORD:}