server:
  port: ${SERVICE_PORT:8080}
spring:
  profiles:
    include:
      - datasources
  application:
    name: mapco-service-public
  datasource:
    modyo:
      url: ${PERSISTENCE_MODYO_URL:jdbc:mysql://127.0.0.1:3306/mapco?useSSL=false}
      username: ${PERSISTENCE_MODYO_USER:root}
      password: ${PERSISTENCE_MODYO_PASSWORD:12345678}
      ddl-auto: ${PERSISTENCE_MODYO_DLL_AUTO:update}
      show-sql: ${PERSISTENCE_MODYO_SHOW_SQL:true}
      hikari:
        connectionTimeout: ${PERSISTENCE_MODYO_CONNECT_TIMEOUT:30000}
        idleTimeout: ${PERSISTENCE_MODYO_IDLE_TIMEOUT:600000}
        maxLifetime: ${PERSISTENCE_MODYO_MAX_LIFETIME:1800000}
        maximumPoolSize: ${PERSISTENCE_MODYO_MAX_POOL_SIZE:1}